### ISSUE TITLE
Buildmaster not listening on port

### ISSUE THREAD

**Issue by jimmykim1** [buildbot/buildbot#4237]
I'm trying to run Buildbot from a docker-compose file on my computer, using the images for buildmaster and worker provided by Buildbot. I define the buildmaster port to be 9989, and in my master.cfg I define a PBChangeSource that listens at port 9989. However, it seems that after I run docker-compose up, there is no process listening at port 9989 (after running `lsof -nP -iTCP:9989 | grep LISTEN`). This seems to be further backed by the fact that when I run `buildbot sendchange -m my.0.0.ip:9989 -a Jimmy:secret -W buildbot`, the twisted server times out, just as it does if I run the same command using a different port, e.g. `buildbot sendchange -m my.0.0.ip:5000 -a Jimmy:secret -W buildbot`. Is this a bug, or is something wrong with my configuration? It's worth noting that in the terminal, I get the messages 
```
buildbot_1  | 2018-07-26 15:31:08+0000 [-] PBServerFactory starting on 9989 
buildbot_1  | 2018-07-26 15:31:08+0000 [-] Starting factory <twisted.spread.pb.PBServerFactory instance at 0x7f49a2780878>
```
, and 
```
worker_1    | 2018-07-26 15:31:10+0000 [-] Starting factory <buildbot_worker.pb.BotFactory instance at 0x7fdf07e7d3b0>
worker_1    | 2018-07-26 15:31:10+0000 [-] Connecting to buildbot:9989
```
, which would suggest nothing is wrong.

Here is a snippet of my master.cfg: 

```
# -*- python -*-
# ex: set filetype=python:

import os

from buildbot.plugins import *

c = BuildmasterConfig = {}

####### WORKERS

c['workers'] = [worker.Worker("example-worker", 'pass')]

if 'BUILDBOT_MQ_URL' in os.environ:
    c['mq'] = {
        'type' : 'wamp',
        'router_url': os.environ['BUILDBOT_MQ_URL'],
        'realm': os.environ.get('BUILDBOT_MQ_REALM', 'buildbot').decode('utf-8'),
        'debug' : 'BUILDBOT_MQ_DEBUG' in os.environ,
        'debug_websockets' : 'BUILDBOT_MQ_DEBUG' in os.environ,
        'debug_lowlevel' : 'BUILDBOT_MQ_DEBUG' in os.environ,
    }
c['protocols'] = {'pb': {'port': os.environ.get("BUILDBOT_WORKER_PORT",9989)}}

####### CHANGESOURCES

c['change_source'] = changes.PBChangeSource(port=9989 , user = 'Jimmy' , passwd = 'secret')

####### SCHEDULERS

# Configure the Schedulers, which decide how to react to incoming changes.  In this
# case, just kick off a 'runtests' build

c['schedulers'] = []
c['schedulers'].append(schedulers.SingleBranchScheduler(
                            name="all",
                            change_filter=util.ChangeFilter(branch='master'),
                            treeStableTimer=None,
                            builderNames=["runtests"]))
c['schedulers'].append(schedulers.ForceScheduler(
                            name="force",
                            builderNames=["runtests"]))


####### DB URL

c['db'] = {
    # This specifies what database buildbot uses to store its state.  You can leave
    # this at its default for all but the largest installations.
    'db_url' : os.environ.get("BUILDBOT_DB_URL", "sqlite://").format(**os.environ),
}

```
Additionally, my docker-compose.yml: 
```
version: '2'
services:
  buildbot:
    image: "buildbot/buildbot-master:master"
    env_file:
      - db.env
    environment:
      - BUILDBOT_CONFIG_DIR=config
      - BUILDBOT_CONFIG_URL=https://github.com/jimmykim1/learning-buildbot/archive/master.tar.gz
      - BUILDBOT_WORKER_PORT=9989
      - BUILDBOT_WEB_URL=http://localhost:8010/
      - BUILDBOT_WEB_PORT=tcp:port=8010
    links:
      - db
    depends_on:
      - db
  db:
    env_file:
      - db.env
    image: "postgres:9.4"
    expose:
      - 5432

  worker:
    image: "buildbot/buildbot-worker:master"
    environment:
      BUILDMASTER: buildbot
      BUILDMASTER_PORT: 9989
      WORKERNAME: example-worker
      WORKERPASS: pass
      WORKER_ENVIRONMENT_BLACKLIST: DOCKER_BUILDBOT* BUILDBOT_ENV_* BUILDBOT_1* WORKER_ENVIRONMENT_BLACKLIST

    links:
      - buildbot

```
