### ISSUE TITLE
Default shell is sh on Unix workers

### ISSUE THREAD

**Issue by vdsbenoit** [buildbot/buildbot#4583]
### Issue
According to workers' code, ``sh`` is used as default shell on Unix workers. However some softwares do not work properly with sh.

### Example
In my case, I use conda environments. The ``conda activate`` command works on Windows and on Linux but not with sh. I would like to avoid being forced to add bash ``-c`` prefix to every build shell step. In this situation I would have to rewrite all the step for Windows and for Linux with different prefixes. 

### Question
Would it be possible to either set bash as default shell on Unix worker or make it configurable?

worker/buildbot_worker/runprocess.py:L469-480
````python
            if runtime.platformType == 'win32':
                # allow %COMSPEC% to have args
                argv = os.environ['COMSPEC'].split()
                if '/c' not in argv:
                    argv += ['/c']
                argv += [self.command]
                self.using_comspec = True
            else:
                # for posix, use /bin/sh. for other non-posix, well, doesn't
                # hurt to try
                argv = [b'/bin/sh', b'-c', self.command]
            display = self.fake_command
````

**Comment by tardyp** [comment]
There is not much point to make this configurable, as you can just simply use the list form of the ShellCommand command parameter.

```python
ShellCommand(command=['/bin/bash', '-c', 'conda activate; pip install buildbot' ])
```

**Comment by vdsbenoit** [comment]
I the case of Buildbot-travis, I would have to specify what shell to use in every build step. Also, I would have to make different build steps with condition filter according to the os.

for instance:
````yml
script:
  - title: install package
    condition: ('windows' in os)
    shell: cmd
    cmd: |
      conda activate my_env
      conda install package

  - title: install package
    condition: ('linux' in os)
    shell: bash
    cmd: |
      conda activate my_env
      conda install package
````

Maybe it is more a Buildbot-travis issue then.

**Comment by vdsbenoit** [comment]
I've just tested your solution and it does not work...

Performing
````python
ShellCommand(command=['bash', '-c', 'conda activate my_env; pip install buildbot' ])
````
will actually result in this (according to the log):
````shell
0 bash -c "conda activate my_env; pip install buildbot"
...
39 CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
40 To initialize your shell, run
41
42     $ conda init <SHELL_NAME> 
43 
44 Currently supported shells are:
45   - bash
46   - fish
47   - tcsh
48   - xonsh
49   - zsh
50   - powershell
51 
52 See 'conda init --help' for more information and options.
53 
54 IMPORTANT: You may need to close and restart your shell after running 'conda init'.

````

While on my worker, if I run bash and use ``conda activate`` I have no issues.

**Comment by rodrigc** [comment]
How does your shell need to be initialized to use `conda`?  Is there some `bashrc` file that isn't being read?

If you do:

```
ShellCommand(command=['/bin/bash', '-l', '-c', 'conda activate; pip install buildbot' ])
```

Do you get different behavior?

**Comment by tardyp** [comment]
bbtravis is just a wrapper around ShellCommand in order to choose the shell, you can just do:

```yaml
script:
  - title: install package
    condition: ('windows' in os)
    cmd: 
        - PowerShell
        - "-command"
        - |
           conda activate my_env
           conda install package

  - title: install package
    condition: ('linux' in os)
    cmd: 
      - /bin/bash
      - "-c"
      - |
        conda activate my_env
        conda install package
```

as per why your example do not work, I am not sure. On windows, sometimes you can have several bash (mingw, git-bash, cygwin) Perhaps, the bash that is first the path as seen per buildbot is not liked by conda, and is not the same as when you test manually.

**Comment by vdsbenoit** [comment]
@rodrigc I've tried it also and it leads to the same results. The ``.bashrc`` must be initialized to run ``conda activate``. I did it and I can use ``conda activate`` in the worker's console. It looks like ``conda activate`` must be run while the current shell is one the shells listed in the error I shared with you in my previous message.

@tardyp If I follow what you've just said, I will have to write every step twice: once in the windows format and once in the linux format. Which makes the ``.bbtravis.yml`` file heavy and harder to maintain. Knowing that I do not use any Unix-based shell on my Windows workers. I would have to do :
````yml
script:
  - title: install package
    condition: ('windows' in os)
    cmd: 
        - cmd
        - "-c"
        - |
           conda activate my_env
           conda install package

  - title: install package
    condition: ('linux' in os)
    cmd: 
      - /bin/bash
      - "-c"
      - |
        conda activate my_env
        conda install package
````

While if a I can set what shell to use on each worker, I could just write one step which would be compatible with any kinds of worker :
````yml
script:
  - title: install package
    cmd: |
           conda activate my_env
           conda install package
````

Also, running commands with YAML scalars does not work properly. I will soon open a pull request that fix [this issue](https://github.com/buildbot/buildbot_travis/issues/98).
