### ISSUE TITLE
How to configure the buildbot docker container using BUILDBOT_CONFIG_URL

### ISSUE THREAD

**Issue by doberkofler** [buildbot/buildbot#5000]
The documentation of the [official][1] docker container for buildbot expects the `BUILDBOT_CONFIG_URL` environment variable to point to a `.tar.gz` file  accessible via HTTP containing the `master.cfg` file.

- How is this supposed to work if the `master.cfg` file is not a single file but rather imports other files like the `private.py` file?
- Is it also possible configure the docker container with physical configuration files?

```yml
version: '2'
services:
  buildbot:
    image: buildbot/buildbot-master:master
    env_file:
      - db.env
    environment:
      - BUILDBOT_CONFIG_DIR=config
      - BUILDBOT_CONFIG_URL=https://github.com/buildbot/buildbot-docker-example-config/archive/master.tar.gz
      - BUILDBOT_WORKER_PORT=9989
      - BUILDBOT_WEB_URL=http://localhost:8010/
      - BUILDBOT_WEB_PORT=tcp:port=8010
    links:
      - db
    depends_on:
      - db
    ports:
      - "8010:8010"
  db:
    env_file:
      - db.env
    image: "postgres:9.4"
    expose:
      - 5432
```

  [1]: https://docs.buildbot.net/latest/tutorial/docker.html

**Comment by an-ky** [comment]
> Is it also possible configure the docker container with physical configuration files?

You can do this using a volume mount. Just add the following lines to the docker-compose.yml

```yml
services:
  buildbot:
  ...
  volumes: 
    - /path/to/config:/var/lib/buildbot
```
and place the `master.cfg` and all files which are used by it in `/path/to/config` on your host. This directory will be mapped on `/var/lib/buildbot/` inside the container where buildbot looks for configuration files.
After changing the configuration file, `docker-compose down && docker-compose up` to restart the containers and buildbot with the new configuration.
