### ISSUE TITLE
Incorrect generated documentation of Worker REST API

### ISSUE THREAD

**Issue by p12tic** [buildbot/buildbot#6604]
The file for Worker REST API (master/buildbot/spec/types/worker.raml) specifies `configured_on` and `connected_to` members of the Worker resource as follows:

```
    configured_on[]:
        description: list of builders on masters this worker is configured on
        properties:
            builderid: integer
            masterid: integer
    connected_to[]:
        description: list of masters this worker is attached to
        properties:
            masterid: integer
```

However, the generated documentation (https://docs.buildbot.net/3.5.0/developer/raml/worker.html) completely omits the information in the `properties` keys.
