### ISSUE TITLE
long lines in build properties do not wrap

### ISSUE THREAD

**Issue by classabbyamp** [buildbot/buildbot#8068]
example: https://build.voidlinux.org/#/builders/5/builds/62

in a narrow window, it forces horizontal scrolling (note the width of the header):

![image](https://github.com/user-attachments/assets/be802b08-0048-40f6-a343-62aa535de360)

setting
```css
.bb-properties-value {
  text-wrap: pretty;
}
````
 makes it much better:

![image](https://github.com/user-attachments/assets/d5c01fdc-41ab-43b3-9fd7-10a8604561a4)
